/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: '1rem',
      screens: { sm: '640px', md: '768px', lg: '1024px', xl: '1280px' },
    },
    extend: {
      screens: { xs: '400px' },
      colors: {
        "inverse-primary": "#c0000a",
        "primary-fixed-dim": "#ffb4aa",
        "outline": "#ad8883",
        "on-secondary-fixed-variant": "#46464b",
        "surface-container-lowest": "#190a08",
        "on-secondary": "#2f3034",
        "error": "#ffb4ab",
        "on-tertiary": "#003545",
        "secondary-container": "#46464b",
        "inverse-surface": "#fcdbd6",
        "surface-container-high": "#392522",
        "on-background": "#fcdbd6",
        "on-primary-container": "#5c0002",
        "background": "#1f0f0d",
        "on-error": "#690005",
        "surface-container-highest": "#44302d",
        "on-tertiary-fixed-variant": "#004d63",
        "surface-container": "#2d1b18",
        "secondary-fixed-dim": "#c6c6cb",
        "on-tertiary-container": "#002e3c",
        "surface-variant": "#44302d",
        "tertiary": "#68d3fc",
        "secondary": "#c6c6cb",
        "surface-container-low": "#291715",
        "surface": "#1f0f0d",
        "on-primary-fixed": "#410001",
        "on-surface-variant": "#e7bdb7",
        "on-secondary-fixed": "#1a1b1f",
        "tertiary-fixed-dim": "#68d3fc",
        "primary-container": "#ff5545",
        "tertiary-fixed": "#bbe9ff",
        "on-surface": "#fcdbd6",
        "surface-dim": "#1f0f0d",
        "surface-bright": "#493431",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#1d9cc3",
        "primary-fixed": "#ffdad5",
        "on-primary-fixed-variant": "#930005",
        "secondary-fixed": "#e3e2e7",
        "primary": "#ffb4aa",
        "on-secondary-container": "#b5b4ba",
        "on-primary": "#690003",
        "surface-tint": "#ffb4aa",
        "inverse-on-surface": "#402b29",
        "outline-variant": "#5d3f3b",
        "on-tertiary-fixed": "#001f29",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "xl-stitch": "80px",
        "sm-stitch": "12px",
        "md-stitch": "24px",
        "lg-stitch": "48px",
        "xs-stitch": "4px",
        "container-max": "1280px",
        "gutter": "24px"
      }
    },
  },
  plugins: [],
}
